### ISSUE TITLE
Request for ROADMAP text

### ISSUE THREAD

**Issue by hwpplayer1** [connervieira/HealthBox#7]
Hi there,

I'll be happy to learn your roadmap.

Thanks, happy hacking!

**Comment by connervieira** [comment]
This is just a project I work on in my free time between school and work, so its nothing I can really create a concrete road-map with dates and goals for, but I am currently in the process of creating a TODO file. I feel like that should be a good way to lay out goals and objectives without setting concrete times and dates.

Thanks for the interest in the project!
